- DockDoor/Utilities/WindowUtil.swift
Seems to me more clean than going through `NSRunningApplication.runningApplications` >  `tempApp` > `tempApp.bundleURL`.
> Refactor: get bundle url directly using NSWorkspace.shared.urlForApplication

- DockDoor/AppDelegate.swift
- DockDoor/Views/Settings/SettingsView.swift
For good UX, we should apply setting changes immediately when possible
> Feat: change showMenuBarIcon setting without restarting the app

- DockDoor/Utilities/SystemPreferencesHelper.swift
The previous address opened the main Security page and not the Screen Recording page
Tested on macOS 14.5, it may be different in older versions, but currently the project runs on macOS 14 only
> Fix openScreenRecordingPreferences

- DockDoor/Views/Settings/PermView.swift
- DockDoor/Views/Settings/UpdateView.swift
Current situation: the window jumps between different sizes sharply, and in the last two tabs the transition back to the first tabs is cumbersome:
https://github.com/ejbills/DockDoor/assets/78599753/7ceb1b71-a319-4b35-910c-bddfdbed1d6b
Suggested in this PR - minimum 600px width:
https://github.com/ejbills/DockDoor/assets/78599753/31765a4d-3c95-4b70-8a0c-5c8efb17991e
> Feat: set minimum width for settings window

- DockDoor/Utilities/WindowUtil.swift
- DockDoor/Views/HoverWindow.swift
Currently we don't support windows in full screen so there is no need for a "toggle", but in the future we will, so I built it as a toggle and not as "enterFullScreen"
SF Symbols doesn't seem to include the exact full screen icon that apple uses, but it's very similar. I checked in alt-tab-macos and it [uses](https://github.com/lwouis/alt-tab-macos/blob/master/src/ui/generic-components/TrafficLightButton.swift#L120-L133) a custom drawing, which I'm not sure if the different license (GPL-3.0 vs MIT) allows us to copy.
Demo:
https://github.com/ejbills/DockDoor/assets/78599753/25654e49-080a-4bad-af49-b6a22109c805
> Feat: add full-screen toggle button to preview window

- DockDoor/Views/HoverWindow.swift
Motivation: The display of the window title in the preview is intended to add more information to the user, but in the case that the window title is exactly the name of the application and nothing more, it is actually an unnecessary duplication of information, which may also hide important parts of the preview.
> Feat: Hide the window title in the preview window if it's the same as the app name

- DockDoor/Views/Settings/SettingsView.swift
The number can never be decimal because the slider uses steps of 5
> Feat: Remove unnecessary ".00" in Window Cache Lifespan

- DockDoor/Utilities/WindowUtil.swift
- DockDoor/Views/HoverWindow.swift
Adds a button to quit the application, as can be done by right-clicking on the application icon in the Dock
Pressing normally = soft quit, pressing with alt (option) pressed = force quit. 
It imitates Apple:
> Feat: add quit app button to preview window

- DockDoor/Views/Hover Window/WindowPreview.swift
Before:
When using a dark theme in System Settings, there are white corners around the preview image
After:
> fix: preview image radius

- DockDoor/Utilities/WindowUtil.swift
- DockDoor/Views/Hover Window/HoverWindow.swift
- DockDoor/Views/Hover Window/WindowPreview.swift
- DockDoor/Views/Settings/SettingsView.swift
- DockDoor/consts.swift
Continuation of https://github.com/ejbills/DockDoor/pull/87
Since not all apps have the same level of window corner rounding, we simply set a transparent background, and display the window as it is instead of interfering with its shape. In addition, we define the gradient overlay with a mask so that it does not color the transparent corners as well.
There is duplication here in defining the gradient but I haven't found a nice way to avoid it. I would love to learn!
> feat: improve window preview shape

- DockDoor/Views/Settings/SettingsView.swift
> fix: openDelay display format

- DockDoor/AppDelegate.swift
Moved initialization from `applicationDidBecomeActive` (https://github.com/ejbills/DockDoor/pull/90) to `applicationShouldHandleReopen` to ensure the menu bar icon is only shown when the app is reopened, and not on other interactions.
Credit: https://github.com/sindresorhus/System-Color-Picker
closes https://github.com/ejbills/DockDoor/issues/95, closes https://github.com/ejbills/DockDoor/issues/76
> fix: show menu bar icon only on app reopen, not on interact

- DockDoor/Views/Hover Window/HoverWindow.swift
- DockDoor/Views/Settings/SettingsView.swift
- DockDoor/consts.swift
Adds options to configure the Hover Window Title Style.
- Adds Settings option for "Hover Window Title Style"
- Default, Embedded, Popover, and None
- Somewhat breaks HoverView into manageable subviews
Examples:
Embedded:
Popover:
> Feature: Hover Window Title Style

- .github/workflows/update-chnagelog.yml
- CHANGELOG.md
- appcast.xml
At the moment the user only knows that there is an update, but he does not know what is new/fixed. This PR displays an automatically updating changelog within Sparkle's update window.
1. I created CHANGELOG.md using https://github.com/rhysd/changelog-from-release CLI
2. I set up their workflow, to automatically update the file on each new release
3. I set `sparkle:releaseNotesLink` to the address of the changelog file on DockDoor's github pages
expected result:
> feat: show chnagelog in in-app update

- .github/workflows/pr-lint.yml
Enforcing Conventional Commits in the PRs title using https://github.com/amannn/action-semantic-pull-request
The workflow is copied from https://github.com/filebrowser/filebrowser/blob/master/.github/workflows/pr-lint.yaml, you can see this an it in action [here](https://github.com/filebrowser/filebrowser/pull/3235#issuecomment-2119115874).
closes #85
> feat: enforce conventional commits for PRs title

- .github/workflows/update-chnagelog.yml
it's just https://github.com/sparkle-project/Sparkle/blob/2.x/Resources/ReleaseNotesColorStyle.css with a little more specific selectors to overwrite jekyll style
closes https://github.com/ejbills/DockDoor/issues/123
> fix: release notes in dark mode

- DockDoor.xcodeproj/project.pbxproj
- DockDoor/Utilities/PrivateApis.swift
- DockDoor/Utilities/WindowUtil.swift
findWindow (find windowRef (AX Window) by `SCWindow`) using `_AXUIElementGetWindow` closes https://github.com/ejbills/DockDoor/issues/75
> fix: Chrome PWA's

- DockDoor.xcodeproj/project.pbxproj
- DockDoor/Utilities/Extensions.swift
- DockDoor/Views/Hover Window/Traffic Light Buttons.swift
The traffic light buttons mimic those of macOS, and macOS never changes the button's icon color:
https://github.com/ejbills/DockDoor/assets/78599753/7081164a-dba3-47ce-b2b7-87584a6af29c
I checked the colors of the macOS buttons with https://github.com/sindresorhus/System-Color-Picker and set them for our buttons. For the quit button I just used dark purple:
closes https://github.com/ejbills/DockDoor/issues/132
> feat: make traffic lights button symbols colored like macOS buttons

- DockDoor/Views/Hover Window/HoverWindow.swift
- DockDoor/Views/Hover Window/Traffic Light Buttons.swift
- DockDoor/Views/Hover Window/WindowPreview.swift
- DockDoor/Views/Settings/AppearanceSettingsView.swift
- DockDoor/Views/Settings/MainSettingsView.swift
- DockDoor/consts.swift
Throws away all numeric enums; Eliminates trying to remember every time "so what does `0` mean and what does `3` mean?". Eliminates awkward code snippets like this:
```
case 1, 2: // Embed + Popover
Text(appName)
```
```
if  showTitlesOnTiles && ((tileTitlesDisplayMode == 1) || (tileTitlesDisplayMode == 2 && CurrentWindow.shared.showingTabMenu) || (tileTitlesDisplayMode == 3 && !CurrentWindow.shared.showingTabMenu)) {
```
Now it's elegant and clear:
```
case .embedded, .popover:
Text(appName)
```
```
if  showWindowTitle && ((windowTitleDisplayCondition == .always) || (windowTitleDisplayCondition == .windowSwitcherOnly && CurrentWindow.shared.showingTabMenu) || (windowTitleDisplayCondition == .dockPreviewsOnly && !CurrentWindow.shared.showingTabMenu)) {
```
Collects all the types related …
> refactor(defaults): replace numeric enums with named enums; reword keys and variables

- appcast.xml
I think this is because of the [change](https://github.com/ejbills/DockDoor/commit/8e5a929e59f1f12cdb78ce898003c3be1effc73e#diff-a83b2ea9fe264ad87bb237369388273b0ef302202bb1f3e678012edfe85aa4aeR8) from `releaseNotesLink` to `fullReleaseNotesLink`
https://sparkle-project.org/documentation/publishing/#:~:text=Sparkle%20may%20let%20the%20user%20open%20this%20link%20in%20their%20web%20browser We want Sparkle to display the report in its built-in browser, not send a link to the browser.
> fix: release notes loading

- DockDoor/Views/Hover Window/WindowPreview.swift
- DockDoor/Views/Settings/MainSettingsView.swift
- DockDoor/consts.swift
> refactor: HoverTimerActions -> PreviewHoverAction

- DockDoor/Views/Settings/MainSettingsView.swift
The average user should not have an understanding of what "Window Cache" is.
> feat: clearer wording

- DockDoor/Utilities/DockObserver.swift
- DockDoor/Views/Hover Window/SharedPreviewWindowCoordinator.swift
This PR re-calculates the Dock Tile Preview (SharedPreviewWindowCoordinator) to be horizontally/vertically centered to the given dock icon instead of relying on the mouse position.
(As much as I tried to condense `getDockIconFrameAtLocation(_:)` and `getDockIconAtLocation(_:)` together, the frame would be incorrectly calculated, breaking alignment. Someone else feel free to examine this.)
Side note: `hideFullPreviewWindow` is currently marked as private and isn't usable outside its parent class.
> feat: center Dock Tile Preview horizontally/vertically to icon

- DockDoor/Views/Hover Window/SharedPreviewWindowCoordinator.swift
Restore fallback to mouse position behavior if getting the icon's frame fails (e.g., returns zero, is not found). Bug report by @ejbills in #182 (which is closed).
> fix: [SharedPreviewWindowCoordinator] add fall back to mouse location for frame calculations

- DockDoor/Localizable.xcstrings
- DockDoor/Views/Hover Window/Traffic Light Buttons.swift
- DockDoor/Views/Hover Window/WindowPreview.swift
- DockDoor/Views/Hover Window/WindowPreviewHoverContainer.swift
- DockDoor/Views/Settings/AppearanceSettingsView.swift
- DockDoor/consts.swift
Replaces PR https://github.com/ejbills/DockDoor/pull/187.
Additionally:
- Replaces the wording "on hover window" in favor of a clearer wording, "on hover preview", both in the code and in the view
- Corrects the double and misleading wording "window title" in favor of "app name"
- Displays the title of the window for the window changer even if it is the same as the name of the application, because in the window viewer the name of the application is not displayed, so it is not duplicate and unnecessary information
- - I'm uncertain what to do when the user disables "Show app name". Thoughts?
Video:
https://github.com/user-attachments/assets/99c8d196-b6a6-4c5b-abb5-e05aa63ff0cc
> feat: add option to select window title visibility (whenOveringPreview/alwaysVisible)

- DockDoor/AppDelegate.swift
- DockDoor/Utilities/Misc Utils.swift
- DockDoor/Views/Settings/PermissionsSettingsView.swift
- DockDoor/Views/Settings/WindowSwitcherSettingsView.swift
The alert tells the user to "restart" but in practice the app is simply killed and the user has to restart it manually. Now the app will restart itself smoothly.
It's imported from alt-tab, more to come!
> feat: restart the app when needed instead of just quit

- DockDoor/AppDelegate.swift
- DockDoor/Views/Settings/MainSettingsView.swift
The opening is even if the menu bar icon is enabled, because sometimes many applications are open in the menu bar and there is no way to get to the DockDoor menu, so it seems logical to me that it would always be possible to open DockDoor again to get to the settings.
closes https://github.com/ejbills/DockDoor/issues/57
*************
It is still not perfect, when the user disables "Show Menu Bar Icon" the window loses focus, and may be lost. I try to focus it back but it only brings it back forward and doesn't focus it, so it can get lost in some scenarios. In any case, the user can always simply reopen the app from the Launchpad and the settings window will open and focused again.
https://github.com/user-attachments/assets/c54792b5-653e-4a3d-9086-bcc71093827f
It happens because of this: …
> feat: open app settings by relaunch

- DockDoor.xcodeproj/project.pbxproj
- DockDoor/Extensions/AXUIElement.swift
- DockDoor/Utilities/PrivateApis.swift
- DockDoor/Utilities/WindowManipulationObservers.swift
- DockDoor/Utilities/WindowUtil.swift
Use `AXUIElement` extension methods (based of https://github.com/lwouis/alt-tab-macos/blob/master/src/api-wrappers/AXUIElement.swift) for shorter and more readable code
The `AXUIElement` extension it's just a **thin** wrapper over the macOS AX APIs, which saves the call success check and dealing with the `inout` variable and types, etc.
There shouldn't be any functional change
> refactor: use AXUIElement extension

- DockDoor/Views/Hover Window/WindowPreview.swift
trafficLightButtonsPosition and windowTitlePosition flipped in RTL langs because the choice is for example "top left" while swiftUI only accepts a definition of "Leading" or "Trailing", which depends on the context (RTL or LTR)
closes https://github.com/ejbills/DockDoor/issues/261
> fix: correct RTL layout rendering for user-defined element positions

- CNAME
- DockDoor.xcodeproj/project.pbxproj
- DockDoor/AppDelegate.swift
- DockDoor/Components/Marquee.swift
- DockDoor/Utilities/DockObserver.swift
- DockDoor/Utilities/MessageUtil.swift
- DockDoor/Utilities/Misc Utils.swift
- DockDoor/Utilities/WindowUtil.swift
- DockDoor/Views/Hover Window/SharedPreviewWindowCoordinator.swift
- DockDoor/Views/Hover Window/WindowPreview.swift
- DockDoor/Views/Hover Window/WindowPreviewHoverContainer.swift
- DockDoor/Views/Settings/AppearanceSettingsView.swift
- DockDoor/Views/Settings/GradientColorPaletteSettingsView.swift
- DockDoor/Views/Settings/MainSettingsView.swift
- DockDoor/Views/Settings/UpdateSettingsView.swift
- DockDoor/Views/Settings/WindowSwitcherSettingsView.swift
Added support for macOS 13 Ventura.
closes https://github.com/ejbills/DockDoor/issues/211
No change is expected for macOS 14 and above, for older systems support does not include a number of small things such as SmoothGradient ~~or the option to cancel in warning about overlapping elements in the settings~~.
> feat: add support for macOS 13 Ventura

- DockDoor/Views/Settings/AppearanceSettingsView.swift
Mistakenly dropped from https://github.com/ejbills/DockDoor/pull/267
> fix: update previousTrafficLightButtonsPosition on ok

- DockDoor/Utilities/KeybindHelper.swift
- DockDoor/Utilities/WindowUtil.swift
- Fixes window switcher lag by lazily updating the window space cache rather than making the UI wait for the update to process
- Fixes closed windows not being removed from cache
Closes https://github.com/ejbills/DockDoor/issues/273
> fix: Window switcher lag

- DockDoor.xcodeproj/project.pbxproj
- DockDoor/Components/sliderSetting.swift
- DockDoor/Extensions/Formatters/NumberFormatter+Convenience.swift
- DockDoor/Views/Settings/GradientColorPaletteSettingsView.swift
- DockDoor/Views/Settings/MainSettingsView.swift
- remove unused decimal formatter
- create number formatter convenience file with init extension and a couple predefined formats
- update sliderSetting to take an optional NumberFormatter and propagate to TextField
- update settings views to use defined formats as appropriate
[385](https://github.com/ejbills/DockDoor/issues/385)
https://github.com/user-attachments/assets/3755c256-0298-47e6-beb9-dccd6ad9f8f3
I am not familiar with swift or macOS development, so don't know which of these methods is more appropriate. I'd already written my change before the [other change](https://github.com/ejbills/DockDoor/commit/ee6a46398a52b4dc056ef8b3430a1bc939743cc1) went in, and was just dealing with some branch weirdness on my repo since I usually only PR within a repo, not across forks...
Anyway, …
> fix: display decimals for sliders with float steps

- DockDoor/Utilities/KeybindHelper.swift
- DockDoor/Utilities/Window Management/WindowUtil.swift
- When classic ordering is enabled and there are at least two windows, set the initial focus on the second window preview instead of the first.
- This improves switching speed and provides a more intuitive experience, similar to Windows OS behavior.
- Fixes #455 #439 #431
> feat: enhance window switcher by focusing on second preview

- DockDoor.xcodeproj/project.pbxproj
- DockDoor/Utilities/KeybindHelper.swift
- DockDoor/Utilities/Misc Utils.swift
- DockDoor/Utilities/Window Management/WindowManipulationObservers.swift
- DockDoor/Utilities/Window Management/WindowUtil.swift
- DockDoor/Views/Hover Window/SharedPreviewWindowCoordinator.swift
- DockDoor/Views/Hover Window/WindowPreview Supporting/Flow Container Calculations.swift
- DockDoor/Views/Hover Window/WindowPreview Supporting/PreviewStateCoordinator.swift
- DockDoor/Views/Hover Window/WindowPreview Supporting/Window Image Sizing Calculations.swift
- DockDoor/Views/Hover Window/WindowPreview.swift
- DockDoor/Views/Hover Window/WindowPreviewHoverContainer.swift
- DockDoor/Views/Settings/AppearanceSettingsView.swift
closes #458 closes #368 closes [#574](https://github.com/ejbills/DockDoor/issues/574)
perf improvements
activation attempts
queue window switcher
better flow algorithm
remove window states, rely on observed object to track window states
- this is fundamental to changes requested in #368
- - we need to orchestrate window actions in the child window preview when a dock preview is active. this means that we need direct access to the entire window states array from the child view to ensure that the action is reflected in the window preview. to get around having to pass multiple copies of the same windows objects and bloat memory, we strip out the window states entirely and instead back the windows with an observed object. this means we can access the object from child views, orchestrate view …
> feat: allow navigation with arrow keys, select by pressing return

- DockDoor/Localizable.xcstrings
- DockDoor/Utilities/KeybindHelper.swift
- DockDoor/Utilities/Window Management/WindowUtil.swift
- DockDoor/Views/Settings/MainSettingsView.swift
- DockDoor/consts.swift
- Add option to limit Window Switcher to active app only
- Add fullscreen app blacklist to prevent key combinations
- Improve UI with file picker for app selection instead of manual text entry
- Use NSWorkspace.shared.frontmostApplication for reliable app detection
- Support both app names and bundle identifiers for blacklist matching
- Add comprehensive settings UI with add/remove functionality
Closes #615, Closes #562
> Implement frontmost app filtering features
