DockDoor.xcodeproj/project.pbxproj
DockDoor/AppDelegate.swift
DockDoor/DockDoorDebug.entitlements
DockDoor/Utilities/Misc Utils.swift
DockDoor/Views/Settings/SettingsView.swift
DockDoor/Views/Settings/WindowSwitcher.swift
DockDoor/Views/Settings/settings.swift
DockDoor/consts.swift

Adding Setting pane to toggle window switcher on/off

---

README.md

closes https://github.com/ejbills/DockDoor/issues/56

Docs: add traffic light buttons guide

---

DockDoor/Views/Settings/UpdateView.swift

Feat: enhance UpdateView style

---

DockDoor/AppDelegate.swift

closes https://github.com/ejbills/DockDoor/issues/76

fix: show menu bar icon when app icon is clicked

---

DockDoor/Utilities/DockObserver.swift

closes https://github.com/ejbills/DockDoor/issues/8
I'm a little concerned about what it means in terms of performance. On the other hand, we already track - and save - every mouse **movement**, so apparently the addition here is no longer significant? Thoughts?

Feat: close preview when dock icon is clicked

---

DockDoor/AppDelegate.swift
DockDoor/Localization/Localizable.xcstrings
DockDoor/Views/Settings/SettingsView.swift
DockDoor/Views/Settings/settings.swift

make more strings localisable, and update he localization

feat: make more strings localisable

---

DockDoor.xcodeproj/project.pbxproj
DockDoor/AppDelegate.swift
DockDoor/Localization/Localizable.xcstrings
DockDoor/Views/Settings/AppearanceView.swift
DockDoor/Views/Settings/SettingsView.swift
DockDoor/Views/Settings/settings.swift

feat: add an "Appearance" tab in app settings

---

.github/workflows/update-chnagelog.yml

feat: improve release notes style

---

.github/workflows/update-changelog.yml
CHANGELOG.md

the github-action bot does not have permissions to publish a PR on this repo, so I had to sign the user as myself.

fix: Changelog pull request from my user (@ejbills)

---

.github/workflows/update-changelog.yml
CHANGELOG.md

fix: Revert "fix: invalid formatting in changelog "

---

.github/workflows/crowdin-sync.yml

https://github.com/marketplace/actions/crowdin-action#:~:text=The%20commit%20message%20for%20the%20pushed%20changes

chore: set commit_message in crowdin-sync.yml

---

DockDoor/Localizable.xcstrings
DockDoor/Views/Settings/AppearanceSettingsView.swift
DockDoor/Views/Settings/MainSettingsView.swift
DockDoor/Views/Settings/WindowSwitcherSettingsView.swift

- scale pickers to fit
- show number field next of sliders for power users (allows to adjust the value more gently than the slider steps)
Note that the numeric field does not enforce as a limit the maximum value of the slider, this is on purpose, if you disagree with this let me know

feat(settings): scale pickers and add number fields next to sliders

---

README.md

https://github.com/ShlomoCode/DockDoor/tree/patch-4#readme

feat: add app icon to readme

---

DockDoor/Views/Settings/AppearanceSettingsView.swift
DockDoor/Views/Settings/MainSettingsView.swift

feat: improve settings layout

---

DockDoor/Views/Hover Window/WindowPreview.swift
DockDoor/Views/Settings/AppearanceSettingsView.swift
DockDoor/consts.swift

closes https://github.com/ejbills/DockDoor/issues/111

feat: add ability to choose traffic light buttons position

---

DockDoor/AppDelegate.swift
DockDoor/Utilities/Misc Utils.swift
DockDoor/Views/Settings/MainSettingsView.swift
DockDoor/Views/Settings/PermissionsSettingsView.swift

For those who disabled the menu bar icon.

feat: add quit button

---

DockDoor/Views/Settings/MainSettingsView.swift

Our project is still in its early stages. While we don't yet have a comprehensive testing framework, adding tests is encouraged where feasible. If you've added tests or have ideas for future tests, please mention this in your PR description. Testing is optional at this point but will help build a more robust codebase as we grow.

fix: use decimalFormatter in 'preview hover delay' setting

---

README.md

adds homebrew install instructions
https://github.com/ejbills/DockDoor/issues/35

chore: add homebrew installation instructions

---

README.md

Show github's copy button for the brew command:

chore: show copy button for brew command

---

DockDoor/Utilities/WindowUtil.swift

Fixes a mistake made in restoring the logic of `bringWindowToFront` in #242

fix: restore original bringWindowToFront logic

---

DockDoor/Localizable.xcstrings

It seems that the new source string needs to be updated using Xcode for the crowdin integration to know how to pull it.
closes https://github.com/ejbills/DockDoor/issues/253
No

chore: update Localizable.xcstrings file with new keys

---

.github/workflows/update-changelog.yml

- also adds donation link in the changelog

fix: missing branch on release publish action

---

DockDoor/Utilities/WindowManipulationObservers.swift

fix: validate windows on window ui elemnt changed

---

.github/workflows/crowdin-sync.yml

fix: typo in cron syntax

---

README.md

Removes styles for badges, updates default keybind.

chore: minimal changes to README.md

---

index.html

Add Polish to dropdown menu on website

chore: add polish language

---

DockDoor/Localizable.xcstrings
DockDoor/Utilities/SpaceWindowCacheManager.swift
DockDoor/Utilities/WindowManipulationObservers.swift
DockDoor/Utilities/WindowUtil.swift
DockDoor/Views/Hover Window/Traffic Light Buttons.swift
DockDoor/Views/Hover Window/WindowPreview.swift
DockDoor/Views/Hover Window/WindowPreviewHoverContainer.swift

also adds app information to the window switcher

feat: preserve preview when interacting with window elements

---

index.html

chore: add portuguese from brazil

---

index.html

Added class "responsive-img" like all other images so that it fits in the screen

fix: window dragging gif not adapted in index.html

---

DockDoor/AppDelegate.swift
DockDoor/Info.plist

feat: enable silent startup using `LSUIElement`

---

DockDoor/Utilities/DockObserver.swift
DockDoor/Utilities/KeybindHelper.swift
DockDoor/Views/Hover Window/SharedPreviewWindowCoordinator.swift
DockDoor/Views/Hover Window/WindowPreview.swift

fix: move window positioning downstream

---

DockDoor/Utilities/Window Management/WindowManipulationObservers.swift
DockDoor/Utilities/Window Management/WindowUtil.swift

fix: window switcher mru ordering

---

DockDoor.xcodeproj/project.pbxproj
DockDoor/Components/Marquee.swift
DockDoor/Components/MaterialPill.swift
DockDoor/Components/dockStyle.swift
DockDoor/Extensions/SwiftUIUtils.swift
DockDoor/Extensions/View.swift
DockDoor/Views/Hover Window/Special Hover Windows/Calendar/CalendarEmbeddedView.swift
DockDoor/Views/Hover Window/Special Hover Windows/Media/MediaControlsEmbeddedView.swift
DockDoor/Views/Hover Window/WindowPreview.swift
DockDoor/Views/Hover Window/WindowPreviewHoverContainer.swift

fix: border cut off

---

DockDoor/Extensions/View.swift
DockDoor/Localizable.xcstrings

fix: blank previews

---

DockDoor/Views/Hover Window/WindowPreview Supporting/DynamicWindowFrameModifier.swift
DockDoor/Views/Hover Window/WindowPreview.swift

fix: remove aspect ratio

---

DockDoor/Components/Marquee.swift
DockDoor/Localizable.xcstrings
DockDoor/Views/Hover Window/Shared Components/SharedPreviewWindowCoordinator.swift
DockDoor/Views/Settings/AppearanceSettingsView.swift
DockDoor/consts.swift

closes https://github.com/ejbills/DockDoor/issues/678
closes https://github.com/ejbills/DockDoor/issues/644

feat: disable marquee toggle
